language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - echo $GPG_PASSPHRASE | gpg --passphrase-fd 0 keys.asc.gpg  
  - gpg --batch --yes --import keys.asc
deploy:
  -
    provider: script
    script: sh .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: albahrani/dimmingplan
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: sh .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: albahrani/dimmingplan
      tags: true
      jdk: oraclejdk8