language: java
sudo: false
install: true

addons:
  sonarqube:
    branches :
      - master
    token:
      secure: "SOfnsgywGUOLJwVX1gwiCrbrsDD5OIQxAqLmqxOzBbH2F65PWRQVL6KB39vyxbi6oBX0Pr9KqNu3JnHB5177COVSiaksDeM6I9en25BpczLkLJQANpitir7C0y4Vo/JIejwTO9asz+Kq7cqrrTxps0GxWUakamXQy6SuzLjn+7NLLJ2My9Mdw/9Czdifkl7MZpkeTIG9V/8XSE+X+NwnDLejLyARLdnp7+5fupZX3r+5RbBv8E5pQhSYWZpg7jsrgY9W5a7PzorSuiHmdDf4zWQcn4tNWZgxzGGMZ+BHQOcKplu4yOs9M+yuvxqHI5xNl2GG88/JJhsK3dsHvHCMoUzlFN1ykRqvLhpN/OTjfa2TsJVkIZxoYkG+le7fJxStKD0xpcOPpwDtr68KpPpnfY1JzK9RhH61d2cL93iMRtq9ZmtZYD3xuYUyW2gDoB/AJqQcCgGUH0XQYGcx9qIrBKqMLvogGQqeuYdyYc8hPkgaJuA06CuHh+bIqZiQRSa2mflRa8ZelR9ntROFB8bWXCgFBEv/g6yUKH5bIDi4gh6uwPXCiU95QX9UN2lSiPb+jcvpbqGtqiWWNDOPsmg6gmemn7ovJpBZyV+VGQjOISdHlxZPBgCrO5SohTvwP6GkBbXC2UtIUK4PtUgmRA8R0IcyRQ3gxgWCa/eG6Ndenak="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
email: false
