language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2  
addons:
  srcclr: true  
  sonarqube:
    branches:
      - master
      - addmvnprofiles   
before_install:
  - echo $GPG_PASSPHRASE | gpg --passphrase-fd 0 keys.asc.gpg  
  - gpg --batch --yes --import keys.asc      
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -B -V
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn --settings .travis/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar  
deploy:
  -
    provider: script
    script: sh .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: albahrani/dimmingplan
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: sh .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: albahrani/dimmingplan
      tags: true
      jdk: oraclejdk8
