name: Java CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Build with Maven
      run: mvn package --settings .m2/settings.xml --file pom.xml
    - name: Deploy to Github Repo
      run: mvn deploy --settings .m2/settings.xml --file pom.xml
